services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=explorewithme
      - SPRING_DATASOURCE_PASSWORD=explorewithme

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: explorewithme
      POSTGRES_PASSWORD: explorewithme
    volumes:
      - stats_data:/var/lib/postgresql/data
      - ./stats-service/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: explorewithme
      POSTGRES_PASSWORD: explorewithme
    volumes:
      - ewm_data:/var/lib/postgresql/data

volumes:
  stats_data:
  ewm_data: